DTItool/urls.py
from django.urls import path
from DTItool import views

app_name = 'DTItool'


urlpatterns = [
    path('', views.index, name='index'),
    path('startup', views.startup, name='startup'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('search/drug/<str:drug_name>', views.search_for_drug, name='search_drug'),
    path('search/protein/<str:protein_name>', views.search_for_protein, name='search_protein'),
    path('condition/drug/<str:drug_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>', views.condition_for_drug, name='condition_drug'),
    path("condition/protein/<str:protein_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>", views.condition_for_protein, name="condition_protein"),
    path('ranking/drug/<str:drug_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.ranking_for_drug, name='ranking_drug'),
    path('ranking/protein/<str:drug_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.ranking_for_protein, name="ranking_protein"),
    path('search/protein/<str:protein_name>', views.search_for_protein, name="search_protein"),
    path('excel/drug/<str:drug_name>', views.drug_excel, name='drug_excel'),
    path('excel/protein/<str:protein_name>', views.excel_for_protein, name='protein_excel'),
    path('excel/drug/<str:drug_name>/dtinet/', views.drug_excel_dtinet, name='drug_excel_dtinet'),
    path('excel/drug/<str:drug_name>/neodti/', views.drug_excel_neodti, name='drug_excel_neodti'),
    path('excel/condition/drug/<str:drug_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>', views.excel_condition),
    path('excel/ranking/drug/<str:drug_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.excel_ranking),
    path('excel/condition/protein/<str:protein_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>', views.excel_condition_protein),
    path('excel/ranking/protein/<str:protein_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.excel_ranking_protein),
]

data_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('lab.urls')),
    path('admin/', admin.site.urls),
    path('DTItool/', include('DTItool.urls')),
] + staticfiles_urlpatterns()

lab/urls.py
from django.urls import path
from lab import views
app_name = 'lab'


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('gene', views.gene, name='gene'),
    path('gene/<str:gene_name>', views.gene_detail, name='gene-detail'),
    # path('search_compound/<str:compound_name>', views.compound, name='compound'),
    path('compound', views.compound, name='compound'),
    path('compound/<str:category>', views.compound, name='compound'),
    path('gene_detail/<str:gene_id>', views.gene_detail, name='gene-detail'),
    path('compound_detail/<str:compound_id>', views.compound_detail, name="compound-detail"),
    path('get_compound_by_name/<str:compound_name>', views.get_compound_by_name, name='get-compound-by-name'),
    path('get_genes_by_name/<str:gene_name>', views.get_genes_by_name, name='get-genes-by-name'),
    path('get_compound_by_category/<str:category>', views.get_compound_by_category, name='get-compound-by-category'),
    path('get_known_targets/<str:compound_id>', views.get_known_targets, name='get-known-targets'),
    path('get_associated_targets/<str:compound_id>', views.get_associated_targets, name='get-associated-targets'),
    path('get_associated_compounds/<str:gene_id>', views.get_associated_compounds, name='get-associated-compounds'),
    path(
        'get_supported_entries_by_drug_id/<str:drug_id>',
        views.get_supported_entries_by_drug_id,
        name='get-supported-entries-by-drug-id'
    ),
    path(
        'get_supported_entries_by_ids/<str:target_id>/<str:drug_id>',
        views.get_supported_entries_by_ids,
        name='get-supported-entries-by-ids'
    ),
    path('statistics', views.statistics, name='statistics'),
    path('help', views.help, name='help'),
    path('get_score_frequency/<str:id>', views.get_score_frequency, name='score-frequency')
]

DTItool/models.py
from django.db import models

# Create your models here.

DTItool/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': 'Password'}))


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'})
        }

DTItool/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as f_login, logout as f_logout
from django.contrib.auth.decorators import login_required


from openpyxl import load_workbook
from io import BytesIO

from DTItool.forms import LoginForm, RegisterForm, UploadExcelForm
from DTItool.mongo_model import db
from utils import export, excel_append

GLOBAL_ENTRIES = {}
# Create your views here.
@login_required(login_url='/DTItool/login')
def index(request):
    if request.method == 'POST':
        form = UploadExcelForm(request.POST, request.FILES)
        if form.is_valid():
            excel = request.FILES['file']
            buffered_stream = BytesIO(excel.read())
            workbook = load_workbook(filename=buffered_stream)
            buffered_stream.close()
            excel_append.append_score(workbook)
            
            workbook.close()
            return HttpResponse('upload succeed')
        else:
            return render(request, 'DTItool/index.html', context={'form': form})
    else:
        f_logout(request)
        form = UploadExcelForm()
    return render(request, 'DTItool/index.html', context={'form': form})


@login_required(login_url='/DTItool/login')
def startup(request):
    # f_logout(request)
    return render(request, 'DTItool/startup.html')

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                f_login(request, user)
                return redirect('DTItool:startup')
            else:
                return render(request, 'DTItool/login.html', context={'form': form})
    else:
        form = LoginForm()
    return render(request, 'DTItool/login.html', context={'form': form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username=username, password=password)
            f_login(request, user)
            return redirect('DTItool:startup')
    else:
        form = RegisterForm()
    return render(request, 'DTItool/register.html', context={'form': form})


def logout(request):
    f_logout(request)
    return HttpResponse('Log out successfully.')

def search_for_drug(request, drug_name):
    result = {
        "ok": False,
        "content": {
            "DTInet": "",
            "NeoDTI": ""
        }
    }
    dtinet_score_entries = db.get_score_entries(drug_name, 'DTInet')
    neodti_score_entries = db.get_score_entries(drug_name, 'NeoDTI')
    if dtinet_score_entries is None or neodti_score_entries is None:
        return JsonResponse(result)
    else:
        result["ok"] = True

    result["content"]['DTInet'] = dtinet_score_entries
    result['content']['NeoDTI'] = neodti_score_entries

    return JsonResponse(result)


def search_for_protein(request, protein_name):
    result = {
        "ok": True,
        "content": "shit"
    }
    result['content'] = db.get_drug_entries(protein_name)
    global GLOBAL_ENTRIES
    GLOBAL_ENTRIES = {
        'protein_name': protein_name,
        'score_entries': result['content']
    }
    return JsonResponse(result)


def drug_excel(request, drug_name):
    dtinet_score_entries = db.get_score_entries(drug_name, 'DTInet')
    neodti_score_entries = db.get_score_entries(drug_name, 'NeoDTI')
    content = export.excel_both(drug_name, dtinet_score_entries, neodti_score_entries)
    response = HttpResponse(content, content_type="application/vnd.ms-excel")
    response['Content-Disposition'] = "attachment; filename={}.xlsx".format(drug_name)

    return response


def excel_for_protein(request, protein_name):
    if GLOBAL_ENTRIES.get('protein_name') != protein_name:
        name = protein_name
        score_entries = db.get_drug_entries(protein_name)
        titles = score_entries[0].keys()
        content = export.common_singlesheet_excel(score_entries, titles, 'scores')
    else:
        name = GLOBAL_ENTRIES['protein_name']
        titles = GLOBAL_ENTRIES['score_entries'][0].keys()
        content = export.common_singlesheet_excel(GLOBAL_ENTRIES['score_entries'], titles, 'scores')
    response = HttpResponse(content, content_type="application/vnd.ms-excel")
    response['Content-Disposition'] = "attachment; filename={} .xlsx".format('protein ' + name)
    
    return response


def drug_excel_dtinet(request, drug_name):
    dtinet_score_entries = db.get_score_entries(drug_name, 'DTInet')
    content = export.excel_dtinet(dtinet_score_entries)
    response = HttpResponse(content, content_type="application/vnd.ms-excel")
    response['Content-Disposition'] = "attachment; filename={} DTInet.xlsx".format(drug_name)
    
    return response


def drug_excel_neodti(request, drug_name):
    neodti_score_entries = db.get_score_entries(drug_name, 'NeoDTI')
    content = export.excel_neodti(neodti_score_entries)
    response = HttpResponse(content, content_type="application/vnd.ms-excel")
    response['Content-Disposition'] = "attachment; filename={} NeoDTI.xlsx".format(drug_name)
    
    return response


def condition_for_drug(request, drug_name, dtinet_upper_limit, dtinet_lower_limit, neodti_upper_limit, neodti_lower_limit):
    result = {
        'ok': False,
        'content': ''
    }
    dtinet_upper_limit = float(dtinet_upper_limit)
    dtinet_lower_limit = float(dtinet_lower_limit)
    neodti_upper_limit = float(neodti_upper_limit)
    neodti_lower_limit = float(neodti_lower_limit)

    dtinet_score_entries = db.get_score_entries_by_drug_condition('DTInet', drug_name, dtinet_upper_limit, dtinet_lower_limit)
    neodti_score_entries = db.get_score_entries_by_drug_condition('NeoDTI', drug_name, neodti_upper_limit, neodti_lower_limit)
    if dtinet_score_entries is None or neodti_score_entries is None:
        return JsonResponse(result)
    else:
        result['ok'] = True
    for dtinet in dtinet_score_entries:
        for neodti in neodti_score_entries:
            if dtinet['protein_id'] == neodti['protein_id']:
                dtinet['NeoDTI_score'] = neodti['NeoDTI_score']
            else:
                dtinet['NeoDTI_score'] = ''
    result['content'] = dtinet_score_entries
    return JsonResponse(result)

def condition_for_protein(request, protein_name, dtinet_upper_limit, dtinet_lower_limit, neodti_upper_limit, neodti_lower_limit):
    result = {
        "ok": True,
        "content": ""
    }
    dtinet_upper_limit = float(dtinet_upper_limit)
    dtinet_lower_limit = float(dtinet_lower_limit)
    neodti_upper_limit = float(neodti_upper_limit)
    neodti_lower_limit = float(neodti_lower_limit)

    dtinet_score_entries = db.get_score_entries_by_protein_condition("DTInet", protein_name, dtinet_upper_limit, dtinet_lower_limit)
    neodti_score_entries = db.get_score_entries_by_protein_condition("NeoDTI", protein_name, neodti_upper_limit, neodti_lower_limit)

    if dtinet_score_entries is None or neodti_score_entries is None:
        return JsonResponse(result)
    else:
        result['ok'] = True

    for dtinet in dtinet_score_entries:
        for neodti in neodti_score_entries:
            if dtinet['drug_id'] == neodti['drug_id']:
                dtinet['NeoDTI_score'] = neodti['NeoDTI_score']
                dtinet["NeoDTI_ranking"] = neodti["NeoDTI_ranking"]
            else:
                dtinet['NeoDTI_score'] = ""
                dtinet["NeoDTI_ranking"] = ""
    result['content'] = dtinet_score_entries
    return JsonResponse(result)

def ranking_for_drug(request, drug_name, dtinet_upper_ranking, dtinet_lower_ranking, neodti_upper_ranking, neodti_lower_ranking):
    result = {
        'ok': False,
        'content': ''
    }
    dtinet_score_entries = db.get_score_entries_by_ranking('DTInet', drug_name, dtinet_upper_ranking, dtinet_lower_ranking)
    neodti_score_entries = db.get_score_entries_by_ranking('NeoDTI', drug_name, neodti_upper_ranking, neodti_lower_ranking)

    if dtinet_score_entries is None or neodti_score_entries is None:
        return JsonResponse(result)
    else:
        result['ok'] = True
    for dtinet in dtinet_score_entries:
        for neodti in neodti_score_entries:
            if dtinet['protein_id'] == neodti['protein_id']:
                dtinet['NeoDTI_ranking'] = neodti['NeoDTI_ranking']
            else:
                dtinet['NeoDTI_ranking'] = ''
    result['content'] = dtinet_score_entries
    return JsonResponse(result)

def ranking_for_protein(request, drug_name, dtinet_upper_ranking, dtinet_lower_ranking, neodti_upper_ranking, neodti_lower_ranking):
    result = {
        "ok": False,
        "content": ""
    }

    dtinet_score_entries = db.get_score_entries_by_protein_ranking('DTInet', drug_name, dtinet_upper_ranking, dtinet_lower_ranking)
    neodti_score_entries = db.get_score_entries_by_protein_ranking('NeoDTI', drug_name, neodti_upper_ranking, neodti_lower_ranking)

    if dtinet_score_entries is None or neodti_score_entries is None:
        return JsonResponse(result)
    else:
        result['ok'] = True
    
    for dtinet in dtinet_score_entries:
        for neodti in neodti_score_entries:
            if dtinet['drug_id'] == neodti['drug_id']:
                dtinet['NeoDTI_score'] = neodti['NeoDTI_score']
                dtinet["NeoDTI_ranking"] = neodti["NeoDTI_ranking"]
            else:
                dtinet['NeoDTI_score'] = ""
                dtinet["NeoDTI_ranking"] = ""
    result['content'] = dtinet_score_entries

DTItool/templates/DTItool/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/semantic.js' %}"></script>
    <script src="https://cdn.staticfile.org/axios/0.19.0-beta.1/axios.min.js"></script>
</head>

<body>
    <header class="y-vertical-center">
        <img src="{% static 'images/logo.png' %}" class="logo" alt="">
    </header>
    <div class="tab-tit y-vertical-center">
        <a href="{% url 'DTItool:startup' %}">起步</a>
        <a href="#" class="cur">综合</a>
    </div>
    <!-- <form method="POST", action="{% url 'DTItool:index' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form> -->
    <form id="form" class="con" method="POST", action="{% url 'DTItool:index' %}" enctype="multipart/form-data">
        <p class="choose-file">选择文件</p>
        <div class="upload">
            <span class="tit chosse-tit">选择</span>
            <span id="upload-file" class="ipt-file">xxxxxxx.xxxx</span>
            <!-- {{ form.excel }} -->
            {% csrf_token %}
            <label class="inputBtn" for="{{ form.file.id_for_label}}">上传</label>
            {{ form.file }}
            <!-- <input type="submit"> -->
            <!-- <input type="file" name="myFile" class="fileipt" id="uploadipt"> -->
        </div>
        <div class="joint">
            <span class="tit">已选择</span>
            <span id="upload-file2" class="ipt-file">xxxxxxx.xxxx</span>
            <label id="joint" class="inputBtn" name='joint' for="1">joint</label>
            <!-- <input type="file" name="joint" class="fileipt" id="1"> -->
        </div>
        <h2>ADVANCED：</h2>
        <div class="item"><span class="tit">DTINet score：</span> <input type="text"> - <input type="text"></div>
        <div class="item"><span class="tit">NeoDTI score：</span> <input type="text"> - <input type="text"></div>
        <div class="item"><span class="tit">DTINet rank： </span> <input type="text"> - <input type="text"></div>
        <div class="item"><span class="tit">NeoDTI rank： </span> <input type="text"> - <input type="text"></div>
        <div class="btn">提交条件</div>
        <!-- <button></button> -->
    </form>
    <div class="form-wrap clearfix">
        <div class="btn">导出</div>
        <div class="form">
            <div class="tr">
                <div class="td">GENE NAME</div>
                <div class="td">CATAGORIES</div>
                <div class="td">PROTEIN NAME</div>
                <div class="td">ASSOCIATE COMPOUND NUMBER</div>
            </div>
            <div class="tr">
                <div class="td">Bearinmind plus 5TD</div>
                <div class="td">GPCR</div>
                <div class="td">alcapa kinase</div>
                <div class="td">12</div>
            </div>
            <div class="tr">
                <div class="td">Bearinmind plus 5TD</div>
                <div class="td">GPCR</div>
                <div class="td">alcapa kinase</div>
                <div class="td">12</div>
            </div>
            <div class="tr">
                <div class="td">Bearinmind plus 5TD</div>
                <div class="td">GPCR</div>
                <div class="td">alcapa kinase</div>
                <div class="td">12</div>
            </div>
            <div class="tr">
                <div class="td">Bearinmind plus 5TD</div>
                <div class="td">GPCR</div>
                <div class="td">alcapa kinase</div>
                <div class="td">12</div>
            </div>
            <div class="tr">
                <div class="td">Bearinmind plus 5TD</div>
                <div class="td">GPCR</div>
                <div class="td">alcapa kinase</div>
                <div class="td">12</div>
            </div>
            <div class="tr">
                <div class="td"></div>
                <div class="td"></div>
                <div class="td"></div>
                <div class="td"></div>
            </div>
        </div>
    </div>
</body>
<script>
    document.getElementById('id_file').onchange = function (e) {
        var uploadFile = document.getElementById('id_file').files[0];
        // 文件名uploadFile
        // console.log(uploadFile)
        // 路径e.target.value
        // console.log(e.target.value)
        document.getElementById('upload-file').innerHTML = e.target.value
        document.getElementById('upload-file2').innerHTML = e.target.value

    }
    document.getElementById("joint").onclick = function(e) {
        // let bodyFormData = new FormData()
        // bodyFormData.set('')
        // axios({
        //     method: 'post',
        //     url: "{% url 'DTItool:index' %}",
        //     headers: {
        //         'Content-Type': "multipart/form-data"
        //     }
        // }).then((response) => {
        //     console.log('ok')
        // })
        document.getElementById("form").submit()
    }
    
</script>

</html>

DTItool/templates/DTItool/login.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Standard Meta -->

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/semantic.js' %}"></script>

  <style type="text/css">
    body {
      background-color: #DADADA;
    }

    body>.grid {
      height: 100%;
    }

    .image {
      margin-top: -100px;
    }

    .column {
      max-width: 450px;
    }
  </style>
  <script>
    // $(document)
    //   .ready(function () {
    //     $('.ui.form')
    //       .form({
    //         fields: {
    //           email: {
    //             identifier: 'email',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your e-mail'
    //               },
    //               {
    //                 type: 'email',
    //                 prompt: 'Please enter a valid e-mail'
    //               }
    //             ]
    //           },
    //           password: {
    //             identifier: 'password',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your password'
    //               },
    //               {
    //                 type: 'length[6]',
    //                 prompt: 'Your password must be at least 6 characters'
    //               }
    //             ]
    //           }
    //         }
    //       })
    //       ;
    //   })
    //   ;
  </script>
</head>

<body>

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui image header">
        <div class="content">
          Log-in to your account
        </div>
      </h2>
      <form id="form" action="{% url 'DTItool:login' %}" method="POST" class="ui large form">
        {% csrf_token %}
        <div class="ui stacked secondary  segment">
          <div class="field">
            {{ form.username.errors}}
            <div class="ui left icon input">
              <!-- <input type="text" name="email" placeholder="E-mail address"> -->
              {{ form.username }}
            </div>
          </div>
          <div class="field">
            {{ form.password.errors }}
            <div class="ui left icon input">
              <!-- <input type="password" name="password" placeholder="Password"> -->
              {{ form.password }}
            </div>
          </div>
          <div id="submit-btn" class="ui fluid large teal submit button" style="background: #e96ba2">Login</div>
        </div>

        <div class="ui error message"></div>

      </form>

      <div class="ui message">
        New to us? <a href="{% url 'DTItool:register' %}">Register</a>
      </div>
    </div>
  </div>



</body>
<script>
  $("#submit-btn").click(() => {
    $("#form").submit()
  })
</script>
</html>

DTItool/templates/DTItool/register.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Standard Meta -->

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/semantic.js' %}"></script>

  <style type="text/css">
    body {
      background-color: #DADADA;
    }

    body>.grid {
      height: 100%;
    }

    .image {
      margin-top: -100px;
    }

    .column {
      max-width: 450px;
    }
  </style>
  <script>
    // $(document)
    //   .ready(function () {
    //     $('.ui.form')
    //       .form({
    //         fields: {
    //           email: {
    //             identifier: 'email',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your e-mail'
    //               },
    //               {
    //                 type: 'email',
    //                 prompt: 'Please enter a valid e-mail'
    //               }
    //             ]
    //           },
    //           password: {
    //             identifier: 'password',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your password'
    //               },
    //               {
    //                 type: 'length[6]',
    //                 prompt: 'Your password must be at least 6 characters'
    //               }
    //             ]
    //           }
    //         }
    //       })
    //       ;
    //   })
    //   ;
  </script>
</head>

<body>

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui image header">
        <div class="content">
          Resigter
        </div>
      </h2>
      <form id="form" action="{% url 'lab:register' %}" method="POST" class="ui large form">
        {% csrf_token %}
        <div class="ui stacked secondary  segment">
          <div class="field">
            {{ form.username.errors}}
            <div class="ui left icon input">
              <!-- <input type="text" name="email" placeholder="E-mail address"> -->
              {{ form.username }}
            </div>
          </div>
          <div class="field">
            {{ form.password.errors }}
            <div class="ui left icon input">
              <!-- <input type="password" name="password" placeholder="Password"> -->
              {{ form.password }}
            </div>
          </div>
          <div id="submit-btn" class="ui fluid large teal submit button"style="background: #e96ba2">Submit</div>
        </div>

        <div class="ui error message"></div>

      </form>

      <div class="ui message">
        Welcome!
      </div>
    </div>
  </div>



</body>
<script>
  $("#submit-btn").click(() => {
    $("#form").submit()
  })
</script>
</html>