DTItool/urls.py
from django.urls import path
from DTItool import views

app_name = 'DTItool'


urlpatterns = [
    path('', views.index, name='index'),
    path('startup', views.startup, name='startup'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('search/drug/<str:drug_name>', views.search_for_drug, name='search_drug'),
    path('search/protein/<str:protein_name>', views.search_for_protein, name='search_protein'),
    path('condition/drug/<str:drug_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>', views.condition_for_drug, name='condition_drug'),
    path("condition/protein/<str:protein_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>", views.condition_for_protein, name="condition_protein"),
    path('ranking/drug/<str:drug_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.ranking_for_drug, name='ranking_drug'),
    path('ranking/protein/<str:drug_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.ranking_for_protein, name="ranking_protein"),
    path('search/protein/<str:protein_name>', views.search_for_protein, name="search_protein"),
    path('excel/drug/<str:drug_name>', views.drug_excel, name='drug_excel'),
    path('excel/protein/<str:protein_name>', views.excel_for_protein, name='protein_excel'),
    path('excel/drug/<str:drug_name>/dtinet/', views.drug_excel_dtinet, name='drug_excel_dtinet'),
    path('excel/drug/<str:drug_name>/neodti/', views.drug_excel_neodti, name='drug_excel_neodti'),
    path('excel/condition/drug/<str:drug_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>', views.excel_condition),
    path('excel/ranking/drug/<str:drug_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.excel_ranking),
    path('excel/condition/protein/<str:protein_name>/<str:dtinet_upper_limit>/<str:dtinet_lower_limit>/<str:neodti_upper_limit>/<str:neodti_lower_limit>', views.excel_condition_protein),
    path('excel/ranking/protein/<str:protein_name>/<int:dtinet_upper_ranking>/<int:dtinet_lower_ranking>/<int:neodti_upper_ranking>/<int:neodti_lower_ranking>', views.excel_ranking_protein),
]

data_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('lab.urls')),
    path('admin/', admin.site.urls),
    path('DTItool/', include('DTItool.urls')),
] + staticfiles_urlpatterns()

lab/urls.py
from django.urls import path
from lab import views
app_name = 'lab'


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('gene', views.gene, name='gene'),
    path('gene/<str:gene_name>', views.gene_detail, name='gene-detail'),
    # path('search_compound/<str:compound_name>', views.compound, name='compound'),
    path('compound', views.compound, name='compound'),
    path('compound/<str:category>', views.compound, name='compound'),
    path('gene_detail/<str:gene_id>', views.gene_detail, name='gene-detail'),
    path('compound_detail/<str:compound_id>', views.compound_detail, name="compound-detail"),
    path('get_compound_by_name/<str:compound_name>', views.get_compound_by_name, name='get-compound-by-name'),
    path('get_genes_by_name/<str:gene_name>', views.get_genes_by_name, name='get-genes-by-name'),
    path('get_compound_by_category/<str:category>', views.get_compound_by_category, name='get-compound-by-category'),
    path('get_known_targets/<str:compound_id>', views.get_known_targets, name='get-known-targets'),
    path('get_associated_targets/<str:compound_id>', views.get_associated_targets, name='get-associated-targets'),
    path('get_associated_compounds/<str:gene_id>', views.get_associated_compounds, name='get-associated-compounds'),
    path(
        'get_supported_entries_by_drug_id/<str:drug_id>',
        views.get_supported_entries_by_drug_id,
        name='get-supported-entries-by-drug-id'
    ),
    path(
        'get_supported_entries_by_ids/<str:target_id>/<str:drug_id>',
        views.get_supported_entries_by_ids,
        name='get-supported-entries-by-ids'
    ),
    path('statistics', views.statistics, name='statistics'),
    path('help', views.help, name='help'),
    path('get_score_frequency/<str:id>', views.get_score_frequency, name='score-frequency')
]

lab/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': 'Password'}))


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'})
        }

class UploadExcelForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField(widget=forms.FileInput({'class': 'fileipt'}))

lab/views.py
from collections import Counter, OrderedDict
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as f_login, logout as f_logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


import copy


from lab.mongo_models import DB
from DTItool.forms import LoginForm, RegisterForm

db = DB()

@login_required(login_url='/login')
def index(request):
    total_numbers = db.get_total_number()
    data = db.get_score_sorted_data()
    context = {
        'subtemplate': 'lab/main.html',
        'data': data,
        'gene_sum': total_numbers['total_gene_number'],
        'compound_sum': total_numbers['total_compound_number'],
        'related_publication_sum': total_numbers['total_related_publication'],
    }
    return render(request, 'lab/index.html', context=context)


@login_required(login_url='/login')
def statistics(request):
    total_numbers = db.get_total_number()
    context = {
        'subtemplate': 'lab/statistics.html',
        'gene_sum': total_numbers['total_gene_number'],
        'compound_sum': total_numbers['total_compound_number'],
        'related_publication_sum': total_numbers['total_related_publication'],
    }
    return render(request, 'lab/index.html', context=context)


@login_required(login_url='/login')
def gene(request):
    context = {
        'subtemplate': 'lab/gene.html',
    }
    return render(request, 'lab/index.html', context=context)


@login_required(login_url='/login')
def gene_detail(request, gene_id):
    gene = db.get_gene_by_id(gene_id)
    context = {
        'subtemplate': 'lab/gene-detail.html',
        'gene': gene
    }
    return render(request, 'lab/index.html', context=context)


@login_required(login_url='/login')
def compound(request, category=None):
    categories = db.get_compound_categories()
    context = {
        'subtemplate': 'lab/compound.html',
        'categories': sorted(categories),

    }
    return render(request, 'lab/index.html', context=context)


@login_required(login_url='/login')
def compound_detail(request, compound_id):
    compound = db.get_compound_by_drugbank_id(compound_id)
    context = {
        'subtemplate': 'lab/compound-detail.html',
        'compound': compound
    }
    return render(request, 'lab/index.html', context=context)


@login_required(login_url='/login')
def help(request):
    context = {'subtemplate': 'lab/help.html'}
    return render(request, 'lab/index.html', context=context)


def get_score_frequency(request, id):
    scores_frequency = db.get_score_frequency(id)
    return JsonResponse(scores_frequency)


def get_compound_by_name(request, compound_name):
    rows = []
    compounds = db.get_compounds_by_name(compound_name)
    for datum in compounds:
        rows.append({
            'id': datum['drugbank_id'],
            'name': datum['drug_name'],
            'categories': datum['categories'],
            'associate_gene_number': len(datum['targets'])
        })
    return JsonResponse({'data': rows})


def get_genes_by_name(request, gene_name):
    genes = db.get_genes_by_name(gene_name)
    return JsonResponse({'data': genes})


def get_compound_by_category(request, category):
    data = db.get_compounds_by_category(category)  # a list of dict
    rows = []
    if category is not None:
        for datum in data:
            row = {
                'id': datum['drugbank_id'],
                'name': datum['drug_name'],
                'categories': datum['categories'],
                'associate_gene_number': len(datum['targets'])
            }
            rows.append(row)
    return JsonResponse({'data': rows})


def get_known_targets(request, compound_id):
    """
    for dti known targets
    :param request:
    :param compound_id:
    :return: JsonResponse
    """
    data = db.get_known_targets(compound_id)
    # for datum in data:
    #     if datum['drugbank_id'] == compound_id:
    #         return JsonResponse({
    #             'targets': datum['targets']
    #         })
    return JsonResponse({'targets': data})


def get_associated_targets(request, compound_id):
    targets = db.get_associated_targets(compound_id)
    return JsonResponse({'targets': targets})


def get_associated_compounds(request, gene_id):
    compounds = db.get_associated_compounds(gene_id)
    return JsonResponse({'compounds': compounds})


def get_supported_entries_by_ids(request, target_id, drug_id):
    supported_entries = db.get_supported_entries_by_ids(target_id, drug_id)
    return JsonResponse(supported_entries)


def get_supported_entries_by_drug_id(request, drug_id):
    supported_entries = db.get_supported_entries_by_drug_id(drug_id)
    return JsonResponse(supported_entries)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                f_login(request, user)
                request.session.set_expiry(10*60)
                return redirect('lab:index')
            else:
                return render(request, 'lab/login.html', context={'form': form})
    else:
        form = LoginForm()
    return render(request, 'lab/login.html', context={'form': form})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username=username, password=password)
            f_login(request, user)
            request.session.set_expiry(10*60)
            return redirect('lab:index')
    else:
        form = RegisterForm()
    return render(request, 'lab/register.html', context={'form': form})

lab/templates/lab/compound.html
<div class="ui segment padded">
  <h2 class="ui header center">SEARCH FOR THE COMPOUND YOU ARE LOOKING FOR:</h2>

  <div class="ui icon input ">
    <input id="compound-name" type="text" placeholder="Search compound...">
    <i id="search-icon" class="circular search link icon"></i>
  </div>
  <div class="ui segment">
    {% for category in categories %}
      <a class="ui tag label">{{ category }}</a>
    {% endfor %}
  </div>
</div>

<div class="ui raised very padded text segment">
  <table id="content-table" class="ui celled table">
    <thead>
    <tr>
      <th>NAME</th>
      <th>CATEGORIES</th>
      <th>ASSOCIATE GENE NUMBER</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<script src="https://cdn.staticfile.org/axios/0.19.0-beta.1/axios.js"></script>
<script>
  $(document).ready(function () {
    $('.ui.tag.label').click(function() {
      let url = '/get_compound_by_category/' + $(this).text()
      axios.get(url)
          .then(function (response) {
            $('#content-table').find('tbody').html(get_represent_data(response.data))
          })
          .catch(function (error) {
            log(error)
          })
    });

    $('#search-icon').click(function () {
      let url = '/get_compound_by_name/' + $('#compound-name').val()
      axios.get(url)
          .then(function (response) {
            $('#content-table').find('tbody').html(get_represent_data(response.data))
          })
          .catch(function (error) {
            log(error)
          })
    });

    function get_represent_data(dataObj) {
      let data = dataObj.data
      let formatted_data = ''
      for (let i=0; i<data.length; i++){
        let categories = data[i].categories.join(', ')
        formatted_data += `
              <tr>
                <td class="compound-name" data-label="NAME"><a href="/compound_detail/${data[i].id}">${data[i].name}</a></td>
                <td data-label="CATEGORIES">${categories}</td>
                <td data-label="ASSOCIATE GENE NUMBER">${data[i].associate_gene_number}</td>
              </tr>
            `
      }
      return formatted_data
    }
  })
</script>

lab/templates/lab/drugs.html
<div class="ui divided items">
  {% for item in data %}
  <div class="item">
    <div class="content">
      {% if forloop.counter == 1 %}
      <div class="header">
        <a href="http://ctdbase.org/basicQuery.go?bqCat=all&bq={{ keyword }}" target="_blank">
          {{ keyword }}
        </a>
      </div>
      {% endif %}
      <div class="description">
        <p>
          {{ item.name }}
        </p>
      </div>
      <div class="extra">
        <div class="ui label">
          score: {{ item.avg_score | floatformat:3 }}
        </div>
        <div class="ui label">
          cite_num: {{ item.cite_num }}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="ui pagination menu">
  <a class="item" href="{% url 'lab:drugs' keyword prev_page %}" id="pagination-pre"> < </a>
  <div class="disable item">
    page {{ page }} of {{ num_pages }}
  </div>
  <a class="item" href="{% url 'lab:drugs' keyword next_page %}" id="pagination-next"> > </a>
</div>

lab/templates/lab/gene.html
<div class="ui segment padded">
  <h2 class="ui header center">SEARCH FOR THE GENE YOU ARE LOOKING FOR:</h2>

  <div class="ui icon input ">
    <input id="gene-name" type="text" placeholder="Search gene...">
    <i id="search-icon" class="circular search link icon"></i>
  </div>
  <div class="ui segment">
{#    <a class="ui tag label">New</a>#}
{#    <a class="ui tag label">Upcoming</a>#}
{#    <a class="ui tag label">Featured</a>#}
  </div>
</div>

<div class="ui raised very padded text segment">
  <table id="content-table" class="ui celled table">
    <thead>
    <tr>
      <th>NAME</th>
      <th>CATEGORIES</th>
      <th>PROTEIN NAME</th>
      <th>ASSOCIATE COMPOUND NUMBER</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<script src="https://cdn.staticfile.org/axios/0.19.0-beta.1/axios.js"></script>
<script>
  $(document).ready(function () {
    {#$('.ui.tag.label').click(function () {#}
    {#  let url = '/get_compound_by_category/' + $(this).text()#}
    {#  axios.get(url)#}
    {#      .then(function (response) {#}
    {#        $('#content-table').find('tbody').html(get_represent_data(response.data))#}
    {#      })#}
    {#      .catch(function (error) {#}
    {#        log(error)#}
    {#      })#}
    {# } );#}

    $('#search-icon').click(function () {
      let url = '/get_genes_by_name/' + $('#gene-name').val();
      axios.get(url)
          .then(function (response) {
            $('#content-table').find('tbody').html(get_represent_data(response.data))
          })
          .catch(function (error) {
            log(error)
          })
    });

    function get_represent_data(dataObj) {
      let data = dataObj.data;
      let formatted_data = '';
      for (let i = 0; i < data.length; i++) {
        formatted_data += `
              <tr>
                <td class="compound-name" data-label="NAME"><a href="/gene_detail/${data[i].id}">${data[i].name}</a></td>
                <td data-label="CATEGORIES"></td>
                <td data-label="PROTEIN NAME">${data[i].protein_name}</td>
                <td data-label="ASSOCIATE COMPOUND NUMBER">${data[i].associate_compound_number}</td>
              </tr>
            `
      }
      return formatted_data
    }
  })
</script>

lab/templates/lab/help.html
<div class="ui raised very padded text segment">
    <div class="ui header">
        COPYRIGHT
    </div>
    <p>
        As the starting point, hit compound identification is a key step in drug discovery process.
        Traditional hit compound identification relies on high-throughput screening assays and is therefore 
        restricted by the diversity and drug-likeness of the compound library used as well as the high cost 
        of experiments. Employing advanced deep learning strategies, our technology manages to capture the 
        meaningful embedded in both compounds and proteins.
    </p>
</div>
<div class="ui raised very padded text segment">
    <div class="ui header">
        FAQ
    </div>
    <p>Q: How does AI read the literature?</p>
    <p>A: TBA</p>
    <p>Q: How can I start with this website?</p>
    <p>A: TBA</p>
</div>

lab/templates/lab/index.html
<!DOCTYPE html>
<html>
{% load static %}
{% load mathfilters %}

<head>
  <meta charset="utf-8">
  <title>IIIS.ThU</title>
  <link rel="stylesheet" href="{% static "css/semantic.css" %}">
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/semantic.js" %}"></script>
  <script src="{% static "js/search.js" %}"></script>
</head>

<body>
    <div class="ui menu">
      <div class="header item">
        <a href="{% url 'lab:index' %}"><p><strong id="textdti" class="bauhs93">TextDTI </strong> POWERED BY SILEXON</p></a>
      </div>
      <div class="item">
      </div>
      <div class="right menu">
        <div class="item" id="menu">
          <a href="{% url 'lab:gene' %}">gene</a>
        </div>
        <div class="item">
          <a href="{% url 'lab:compound' %}">compound</a>
        </div>
        <div class="item">
          <a href="{% url 'lab:statistics' %}">statistics</a>
        </div>
        <div class="item">
          <a href="{% url 'lab:help' %}">help</a>
        </div>
      </div> 
    </div>
    <!-- main content -->
    <div class="ui container">
        {% include subtemplate %}
    </div>
</body>

</html>

lab/templates/lab/login.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Standard Meta -->

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/semantic.js' %}"></script>

  <style type="text/css">
    body {
      background-color: #DADADA;
    }

    body>.grid {
      height: 100%;
    }

    .image {
      margin-top: -100px;
    }

    .column {
      max-width: 450px;
    }
  </style>
  <script>
    // $(document)
    //   .ready(function () {
    //     $('.ui.form')
    //       .form({
    //         fields: {
    //           email: {
    //             identifier: 'email',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your e-mail'
    //               },
    //               {
    //                 type: 'email',
    //                 prompt: 'Please enter a valid e-mail'
    //               }
    //             ]
    //           },
    //           password: {
    //             identifier: 'password',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your password'
    //               },
    //               {
    //                 type: 'length[6]',
    //                 prompt: 'Your password must be at least 6 characters'
    //               }
    //             ]
    //           }
    //         }
    //       })
    //       ;
    //   })
    //   ;
  </script>
</head>

<body>

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui image header">
        <div class="content">
          Log-in to your account
        </div>
      </h2>
      <form id="form" action="{% url 'lab:login' %}" method="POST" class="ui large form">
        {% csrf_token %}
        <div class="ui stacked secondary  segment">
          <div class="field">
            {{ form.username.errors}}
            <div class="ui left icon input">
              <!-- <input type="text" name="email" placeholder="E-mail address"> -->
              {{ form.username }}
            </div>
          </div>
          <div class="field">
            {{ form.password.errors }}
            <div class="ui left icon input">
              <!-- <input type="password" name="password" placeholder="Password"> -->
              {{ form.password }}
            </div>
          </div>
          <div id="submit-btn" class="ui fluid large teal submit button" style="background: #28293d">Login</div>
        </div>

        <div class="ui error message"></div>

      </form>

      <!-- <div class="ui message">
        New to us? <a href="{% url 'DTItool:register' %}">Register</a>
      </div> -->
    </div>
  </div>



</body>
<script>
  $("#submit-btn").click(() => {
    $("#form").submit()
  })
</script>
</html>

lab/templates/lab/register.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Standard Meta -->

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/semantic.js' %}"></script>

  <style type="text/css">
    body {
      background-color: #DADADA;
    }

    body>.grid {
      height: 100%;
    }

    .image {
      margin-top: -100px;
    }

    .column {
      max-width: 450px;
    }
  </style>
  <script>
    // $(document)
    //   .ready(function () {
    //     $('.ui.form')
    //       .form({
    //         fields: {
    //           email: {
    //             identifier: 'email',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your e-mail'
    //               },
    //               {
    //                 type: 'email',
    //                 prompt: 'Please enter a valid e-mail'
    //               }
    //             ]
    //           },
    //           password: {
    //             identifier: 'password',
    //             rules: [
    //               {
    //                 type: 'empty',
    //                 prompt: 'Please enter your password'
    //               },
    //               {
    //                 type: 'length[6]',
    //                 prompt: 'Your password must be at least 6 characters'
    //               }
    //             ]
    //           }
    //         }
    //       })
    //       ;
    //   })
    //   ;
  </script>
</head>

<body>

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui image header">
        <div class="content">
          Resigter
        </div>
      </h2>
      <form id="form" action="{% url 'DTItool:register' %}" method="POST" class="ui large form">
        {% csrf_token %}
        <div class="ui stacked secondary  segment">
          <div class="field">
            {{ form.username.errors}}
            <div class="ui left icon input">
              <!-- <input type="text" name="email" placeholder="E-mail address"> -->
              {{ form.username }}
            </div>
          </div>
          <div class="field">
            {{ form.password.errors }}
            <div class="ui left icon input">
              <!-- <input type="password" name="password" placeholder="Password"> -->
              {{ form.password }}
            </div>
          </div>
          <div id="submit-btn" class="ui fluid large teal submit button"style="background: #e96ba2">Submit</div>
        </div>

        <div class="ui error message"></div>

      </form>

      <div class="ui message">
        Welcome!
      </div>
    </div>
  </div>



</body>
<script>
  $("#submit-btn").click(() => {
    $("#form").submit()
  })
</script>
</html>

lab/templates/lab/semanticwb.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% load mathfilters %}
  <head>
    <meta charset="utf-8">
    <title>IIIS.ThU</title>
    <link rel="stylesheet" href="{% static "css/semantic.css" %}">
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/semantic.js" %}"></script>
    <script src="{% static "js/search.js" %}"></script>
  </head>
  <body>
    <div class="ui thin visible left sidebar inverted vertical menu">
      <div class="header item">
        <img src="{% static "images/logo2.png" %}">
      </div>
      <div class="item">
        Doucument
        <i class="browser icon"></i>
      </div>
      <div class="item">
        Charts
        <i class="bar chart icon"></i>
      </div>
      <div class="item">
        Others
        <i class="idea icon"></i>
      </div>
      <div class="item" id="search">
        Search
        <i class="search icon"></i>
      </div>
      <div class="item" id="search-bar">
        <form action="{% url 'lab:index' %}" method="POST">
          {% csrf_token %}
          <input name="keyword">
          <input type="hidden" name="page" value="1">
        </form>
      </div>
      <a href="{% url 'lab:drugs' 'rivaroxaban' 1 %}">
        <div class="item">
          Gene
          <i class="lab icon"></i>
        </div>
      </a>
      <a href="{% url 'lab:drugs' 'prothrombinase' 1 %}">
        <div class="item">
          Compound
          <i class="database icon"></i>
        </div>
      </a>
      <a href="{% url 'lab:statistics' %}">
        <div class="item">
          Statistics
        </div>
      </a>
      <div class="item">
          <span  style="overflow-wrap: break-word">
          Created by Silexon
          </span>
      </div>
    </div>
    <div class="pusher">


      <div class="ui menu">
        <div class="header item" id="menu">
          Menu
          <i class="content icon"></i>
        </div>
        <div class="item">
          About us
        </div>
        <div class="item">
          Location
        </div>
        <div class="item">
          Others
        </div>

      </div>
      <div class="ui container">
        <div class="ui divided items">
          {% for item in data %}
            <div class="item">
                <div class="content">
                  {% if forloop.counter == 1 %}
                  <div class="header">
                    <a href="http://ctdbase.org/basicQuery.go?bqCat=all&bq={{ keyword }}" target="_blank">
                      {{ keyword }} 
                    </a>
                  </div>
                  {% endif %}
                  <div class="description">
                    <p>
                       {{ item.name }}
                    </p>
                  </div>
                  <div class="extra">
                    <div class="ui label">
                      score:  {{ item.avg_score | floatformat:3 }}
                    </div>
                    <div class="ui label">
                      cite_num:  {{ item.cite_num }}
                    </div>
    
                  </div>
    
                </div>
    
              </div>
          {% endfor %}
          <!-- <div class="item">
            <div class="content">
              <div class="header">
                The title
              </div>
              <div class="description">
                <p>
                  Data 3
                </p>
              </div>
              <div class="extra">
                <div class="ui label">
                  tag1
                </div>
                <div class="ui label">
                  tag2
                </div>

              </div>

            </div>

          </div> -->

        </div>
        <div class="ui pagination menu">
          <a class="item" href="{% url 'lab:drugs' keyword prev_page %}" id="pagination-pre"> < </a>
          <div class="disable item">
            page {{ page }} of {{ num_pages }}
          </div>
          <a class="item" href="{% url 'lab:drugs' keyword next_page %}" id="pagination-next"> > </a>
        </div>
      </div>

    <script>
      $('#menu').click(function () {
        $('.ui.sidebar').sidebar('toggle');
      });
    </script>
    </div>
  </body>
</html>